Add functionality to have job queues with different schedules
Bertverbeek4PS/bc2adls pull request #194
Opened 2024-11-20 12:57 UTC by acjdekorte

One of our customer would like to be able to export some tables every hours, while exporting other tables only once a day. In order to accommodate this, we have extended the functionality with a possibility to have different job queue for the export.

2024-12-11 13:27 UTC, acjdekorte commented
@Bertverbeek4PS Could you please inform us, if you are willing to accept this idea for the standard or if we should continu as customization.

2024-12-11 13:33 UTC, Bertverbeek4PS commented
Sorry @acjdekorte totally overlooked this PR.
I will look into this next week.

2024-12-11 13:35 UTC, acjdekorte commented
Thank you, will wait for your decision

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/AssignExportCategoryDialog.page.al
> +                ToolTip = 'Unique Code of an Export Category which can be linked to tables which are part of the export to Azure Datalake.';
Tooltips always starts with specifies and maybe put it on table level.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ExportCategories.Page.al
> +    UsageCategory = Lists;
Could you remove the usagecategory and please it in the ribbon of bc2adls setup?

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ExportCategories.Page.al
> +                    ToolTip = 'Unique Code of a Export Category which can be linked to tables which are part of the export to Azure Datalake.';
Tooltips always starts with specifies and maybe put it on table level.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ExportCategories.Page.al
> +                    ToolTip = 'Description of the Export Category.';
Tooltips always starts with specifies and maybe put it on table level.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ExportCategory.Table.al
> +
Could you add the LookUpPageId property?

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +    Caption = 'Schedule Execution WRP Tables';
WRP??

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +            RequestFilterFields = "Table ID", ExportCategory, Enabled;
Maybe only mention the export category

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +        trigger OnQueryClosePage(CloseAction: Action): Boolean
please remove this trigger

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +        trigger OnOpenPage()
please remove this trigger

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +    trigger OnInitReport()
please remove this trigger

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +    trigger OnPreReport()
please remove this trigger

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +    trigger OnPostReport()
please remove this trigger

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/Setup.Page.al
> -                    ADLSEExecution.ScheduleExport();
Could you remove this function in Codeunit "ADLSE Execution" and also the local procedure CreateJobQueueEntry to clean up all code

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/Setup.Page.al
> +                ToolTip = 'Show the scheduled Job Queues for the export to Datalake';
Tooltips always starts with specifies

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/SetupTables.Page.al
> +                    ToolTip = 'Export Category which can be linked to tables which are part of the export to Azure Datalake. The Category can be used to schedule the export.';
Tooltips always starts with specifies and maybe put it on table level.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/SetupTables.Page.al
> +                ToolTip = 'Assign an Export Category to the Table.';
Tooltips always starts with specifies and maybe put it on table level.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +                        ToolTip = 'The description that is displayed in the job queue.';
Tooltips always starts with specifies.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +                        ToolTip = 'The date and time when the job queue must be executed for the first time.';
Tooltips always starts with specifies.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +                        ToolTip = 'Specifies the minimum number of minutes that are to elapse between runs of a job queue entry. The value cannot be less than one minute.';
Tooltips always starts with specifies.

2024-12-12 11:03 UTC, Bertverbeek4PS commented on businessCentral/app/src/Table.Table.al
> +        field(10; ExportCategory; Code[50])
Be aware if you already exported the schema and want to change this you get an error. I think that is not a good thing.

2024-12-17 15:54 UTC, Bertverbeek4PS commented
@acjdekorte I have added a couple of comments.

2025-01-06 13:35 UTC, acjdekorte commented
@Bertverbeek4PS My colleague @pvoruganti-mprise just finished the improvements

2025-01-07 07:52 UTC, Bertverbeek4PS requested changes

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +    Caption = 'Schedule Export to Azure Data Lake';
Maybe another caption. Because you can also export to Fabric.
Like: "Schedule Export"

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/Setup.Page.al
> +                    JobQueueEntry.SetRange("Object ID to Run", 11332001);
I think this number is wrong.
Just use no numbers but the name of the report.

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/Setup.Page.al
> +                    MAWBScheduleExecutionTables: Report "ADLSE Schedule Task Assignment";
Could you use the var name:
ADLSEScheduleTask

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/SetupTables.Page.al
> +                    ToolTip = 'Export Category which can be linked to tables which are part of the export to Azure Datalake. The Category can be used to schedule the export.';
Tooltips always starts with specifies and maybe put it on table level.

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/SetupTables.Page.al
> +                ToolTip = 'Assign an Export Category to the Table.';
Tooltips always starts with specifies.

2025-01-07 07:52 UTC, Bertverbeek4PS commented on businessCentral/app/src/ScheduleTaskAssignment.Report.al
> +                        Caption = 'Earliest Start Dqate / Time ';
the q must be removed in the caption.

2025-01-07 07:53 UTC, Bertverbeek4PS commented
> @Bertverbeek4PS My colleague @pvoruganti-mprise just finished the improvements

Thanks!!! I have requested 6 smaller changes and then we are ready to go! 👍

2025-01-07 09:55 UTC, pvoruganti-mprise commented on businessCentral/app/src/SetupTables.Page.al
> +                ToolTip = 'Assign an Export Category to the Table.';
Dear @Bertverbeek4PS ,

Could you please confirm this for me? Should I write the action tooltip using the word Specifies?

Best regards,

2025-01-07 09:58 UTC, Bertverbeek4PS commented on businessCentral/app/src/SetupTables.Page.al
> +                ToolTip = 'Assign an Export Category to the Table.';
Hi @pvoruganti-mprise. Sorry this is an action. 
So indeed no specify. This tooltip is OK. Sorry that I overlooked that!

2025-01-07 12:53 UTC, Bertverbeek4PS approved these changes

2025-01-07 12:53 UTC, merged

2025-01-07 12:54 UTC, Bertverbeek4PS commented
thanks @pvoruganti-mprise and @acjdekorte for this nice much requested feature!!

2025-01-07 13:54 UTC, acjdekorte commented
thanks @Bertverbeek4PS